### PR TITLE
Fix #798.

### LINKED ISSUE #798: `::` is not correctly indented
## Steps

The following test fails:

```
<<< Indent `::` with tuples
val overrides =
      "akka.log-config-on-start" -> "on" ::
      "akka.cluster.split-brain-resolver.static-quorum.quorum-size" -> 1 ::
        "akka.remote.netty.tcp.hostname" -> akkaHost ::
        "akka.remote.netty.tcp.port" -> akkaPort ::
        Nil
>>>
  val overrides =
    "akka.log-config-on-start" -> "on" ::
      "akka.cluster.split-brain-resolver.static-quorum.quorum-size" -> 1 ::
      "akka.remote.netty.tcp.hostname" -> akkaHost ::
      "akka.remote.netty.tcp.port" -> akkaPort ::
      Nil
```

### PR DESCRIPTION
**Pull request by olafurpg**
infixSplit is used for both infix applications, where we want to handle
infix operators, and also for assignment, where we don't want to handle
right associative operators.

This commit is a poor fix/hack/workaround for this issue. I would love
to come with a better design/implementation to avoid this duct taping,
but I'm afraid I don't have so much time right now and I want to publish
a fix quickly.

### CODE REVIEW

**Comment by olafurpg** [comment]
@pjrt The issue is that `infixSplits` is called from here https://github.com/olafurpg/scalafmt/blob/c53f03f7744bd04bef3e56fdcaea6294de48ec1e/core/src/main/scala/org/scalafmt/internal/Router.scala#L893, where `formatToken` is `= "..."` and not the `::` infix application. I'm not sure how to gracefully avoid the right-associativity handling when infixSplit is called from that case, any ideas/suggestions welcome.

Otherwise, I'm OK with just using this hack . I'm hoping to replace Router.scala this summer with the help of a GSoC student http://www.scala-lang.org/gsoc/2017.html#new-line-wrapping-algorithm-for-scalafmt

File: core/src/main/scala/org/scalafmt/internal/FormatOps.scala [hunk 1]
```diff
@@ -476,6 +476,8 @@ class FormatOps(val tree: Tree, val initStyle: ScalafmtConfig) {
     }
     val isRightAssociative =
       style.indent.rightAssociativeInfixOperatorsLikeLeftAssociative &&
+        // NOTE. Silly workaround because we call infixSplit from assignment =, see #798
+        formatToken.left.syntax != "=" &&
```
Comment (pjrt) [inline core/src/main/scala/org/scalafmt/internal/FormatOps.scala]: So the bug happens when making a plain assignment? So the previous test passed because the "left" was never `=`.

**Comment by pjrt** [comment]
I'm ok with this hack atm since this is a pretty large bug. Merging once CI is done.

**Comment by olafurpg** [comment]
Sounds good, I'll merge and publish 0.6.2 then! :shipit:

**Comment by olafurpg** [comment]
The update should hit maven in ~30 min
